name: Run PR Checks

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::389719579847:role/github_actions
  AWS_ROLE_SESSION_NAME: deployer-pr-checks-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  checks:
    runs-on:
    - codebuild-builder-${{ github.run_id }}-${{ github.run_attempt }}
    - image:aws/codebuild/standard:5.0
    - instance-size:medium
    name: Run PR Checks
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Check
      id: check
      env:
        NIX_SHOW_STATS: "0"
        NIX_VERBOSE: "0"
      run: |
        nix develop --quiet --command task lint
        nix develop --quiet --command task test
        nix develop --quiet --command task build
