name: Run PR Checks

on:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_ROLE_ARN: arn:aws:iam::389719579847:role/github_actions
  AWS_ROLE_SESSION_NAME: deployer-pr-checks-${{ github.run_id }}-${{ github.run_attempt }}

jobs:
  checks:
    runs-on:
    - codebuild-builder-${{ github.run_id }}-${{ github.run_attempt }}
    - image:aws/codebuild/standard:5.0
    - instance-size:medium
    name: Run PR Checks
    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure AWS Credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.AWS_ROLE_ARN }}
        role-session-name: ${{ env.AWS_ROLE_SESSION_NAME }}
        aws-region: ${{ env.AWS_REGION }}
        output-credentials: true

    - name: Check
      id: check
      uses: devcontainers/ci@v0.3.1900000417
      with:
        subFolder: ${{ github.workspace }}
        configFile: .devcontainer/CI/devcontainer.json
        env: |
          AWS_REGION=${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID=${{ steps.aws-credentials.outputs.aws-access-key-id }}
          AWS_SECRET_ACCESS_KEY=${{ steps.aws-credentials.outputs.aws-secret-access-key }}
          AWS_SESSION_TOKEN=${{ steps.aws-credentials.outputs.aws-session-token }}
        runCmd: |
          task lint
          task test
          task build
